jdmapi_homepage:
    path:     /jdmapi
    defaults: { _controller: JdmapiBundle:Default:index }

jdmapi_nodepage:
    path:     /node
    defaults: { _controller: JdmapiBundle:Node:index }

jdmapi_showNodeById:
    path: /jdmapi/nodeid/{nodeid}
    defaults: { _controller: JdmapiBundle:Default:showNodeById }

jdmapi_getNodeByNmae:
    path: /jdmapi/node/{nodename}
    defaults: { _controller: JdmapiBundle:Default:getNodeByName }

# Route de test
jdmapi_batch:
    path:     /batch
    defaults: { _controller: JdmapiBundle:Batch:index }

# Route du script d'insertion des nodes
jdmapi_batch_node:
    path:     /batch/node/insert/{relid}
    defaults: { _controller: JdmapiBundle:Batch:insertNodes,
                relid: 0  # absence d'ID de relation
              }
    requirements:
        relid: \d+

# Route du script d'insertion des relations
jdmapi_batch_relation:
    path:     /batch/rel/insert/{relid}
    defaults: { _controller: JdmapiBundle:Batch:insertRels,
                relid: 0   # absence d'ID de relation
              }
    requirements:
        relid: \d+
