services:
#    jdmapi.example:
#        class: UM\JdmapiBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    jdmapi.batch:
        class: UM\JdmapiBundle\Controller\BatchController
