<?php

namespace um\jdmapi\jdmapiBundle\Repository;

/**
 * Type_nodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Type_nodeRepository extends \Doctrine\ORM\EntityRepository
{
}
