<?php

namespace UM\JdmapiBundle\Repository;

/**
 * Type_nodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Node_typeRepository extends \Doctrine\ORM\EntityRepository
{
}
