<?php

namespace UM\jdmapiBundle\Repository;

/**
 * Relation_typeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Relation_typeRepository extends \Doctrine\ORM\EntityRepository
{
}
